spring:
  application:
    name: eureka-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@com.me.com:8761/eureka/
security:
  user:
    name: admin
    password: admin