spring:
  application:
    name: eureka-service
  cloud:
    client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@com.me.com:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
security:
  user:
    name: root
    password: root